#spring.application.name=rfmoodle
server:
  port: 3000

spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/moodle
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: false
  main:
    web-application-type: servlet
  logging:
    level:
      org.springframework.security: DEBUG


application:
  api:
    ver: "api/"
  security:
    jwt:
      secret-key: ad7205a6abfe94462841119255593a6c595e8d477d152875a4db3c4b2d1416d3
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

